language: python

python: "3.6"
cache: pip
install: "pip install -r requirements.txt"
script: 
  - python tests/test_preprocess.py
  - python setup.py install

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always
