apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers: 
        - name: backend
          image: ileefmans/scinet:demo
          ports:
            - containerPort: 80

   
