apiVersion: batch/v1
kind: Job
metadata:
  name: demo-deployment
spec:
  template:
    metadata:
      name: demo-deployment-pod
    spec:
      containers: 
      - name: demo-deployment
        image: demo:1.0
      restartPolicy: Never    
